import io
from xml.sax.saxutils import escape as _xml_escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from src.reports.report_context import ReportContext

# Spec section 1: never imply affiliation with a named consulting firm.
DISCLAIMER = (
    "Strategy-consulting-inspired analysis generated by this application. "
    "Not affiliated with, endorsed by, or reviewed by McKinsey, BCG, Bain, "
    "or any other consulting firm."
)

def _esc(text: str | None) -> str:
    """Escapes text before it's interpolated into a Paragraph string.
    reportlab's Paragraph runs its content through a mini-XML parser (that's
    how `<b>`/`<font>` markup works) — any unescaped LLM- or user-authored
    text containing '<', '>', or '&' that happens to look like a tag crashes
    report generation. Confirmed: `Paragraph('...the <b> tag...', style)`
    raises a parse error at build time. Every dynamic value (company/project
    names included — a user can type "Smith & Sons" as a company name) must
    go through this before being placed inside a Paragraph string, whether or
    not the surrounding string also contains our own literal <b>/<font> markup."""
    return _xml_escape(text) if text else ""


_SEVERITY_COLORS = {
    "LOW": colors.HexColor("#B8860B"),
    "MEDIUM": colors.HexColor("#CC7A00"),
    "HIGH": colors.HexColor("#C0392B"),
    "CRITICAL": colors.HexColor("#8B0000"),
}


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=22, spaceAfter=6))
    styles.add(ParagraphStyle("ReportSubtitle", parent=styles["Normal"], fontSize=12, textColor=colors.grey, alignment=TA_CENTER))
    styles.add(ParagraphStyle("SectionHeading", parent=styles["Heading1"], fontSize=15, spaceBefore=18, spaceAfter=8))
    styles.add(ParagraphStyle("SubHeading", parent=styles["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.grey))
    # Table body cells hold LLM-authored text of unpredictable length; a plain
    # string in a reportlab Table cell does not reliably wrap within a fixed
    # column width the way a Paragraph flowable does — confirmed live: long
    # 90-Day Action Plan text overlapped adjacent cells instead of wrapping.
    styles.add(ParagraphStyle("TableCell", parent=styles["Normal"], fontSize=8, leading=10))
    return styles


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.grey)
    canvas.drawString(0.75 * inch, 0.5 * inch, DISCLAIMER)
    canvas.drawRightString(LETTER[0] - 0.75 * inch, 0.5 * inch, f"Page {doc.page}")
    canvas.restoreState()


def generate_pdf_report(ctx: ReportContext) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        title=f"{ctx.project.name} — Business Consulting Report",
    )
    styles = _styles()
    story = []

    story += _title_page(ctx, styles)
    story.append(PageBreak())

    if ctx.synthesis is not None:
        story += _executive_summary(ctx, styles)
        story += _business_performance(ctx, styles)
        story += _concerns(ctx, styles)
        story += _opportunities(ctx, styles)
        story += _strategic_options(ctx, styles)
        story += _action_plan(ctx, styles)
        story += _missing_information(ctx.synthesis.missing_information, styles)
    else:
        story.append(Paragraph("Executive Synthesis", styles["SectionHeading"]))
        story.append(
            Paragraph(
                "No Deep Analysis run has completed for this project yet. The sections below show "
                "what's already available from documents ingested and analysis run so far.",
                styles["Normal"],
            )
        )
        story += _concerns(ctx, styles)
        story += _opportunities(ctx, styles)

    story += _financial_appendix(ctx, styles)

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


def _title_page(ctx: ReportContext, styles) -> list:
    return [
        Spacer(1, 1.5 * inch),
        Paragraph(_esc(ctx.company.name), styles["ReportTitle"]),
        Paragraph(_esc(ctx.project.name), ParagraphStyle("ProjectName", parent=styles["Heading2"], alignment=TA_CENTER)),
        Spacer(1, 0.3 * inch),
        Paragraph("Business Consulting Report", styles["ReportSubtitle"]),
        Paragraph(f"Generated {ctx.generated_at.strftime('%B %d, %Y')}", styles["ReportSubtitle"]),
        Spacer(1, 1 * inch),
        Paragraph(DISCLAIMER, ParagraphStyle("TitleDisclaimer", parent=styles["Disclaimer"], alignment=TA_CENTER)),
    ]


def _executive_summary(ctx: ReportContext, styles) -> list:
    flow = [
        Paragraph("Executive Summary", styles["SectionHeading"]),
        Paragraph(_esc(ctx.synthesis.overall_assessment), styles["Normal"]),
    ]

    if ctx.synthesis.key_findings:
        flow.append(Paragraph("Key Findings", styles["SubHeading"]))
        flow.append(
            ListFlowable([ListItem(Paragraph(_esc(f), styles["Normal"])) for f in ctx.synthesis.key_findings], bulletType="bullet")
        )

    return flow


def _business_performance(ctx: ReportContext, styles) -> list:
    bp = ctx.synthesis.business_performance
    rows = [
        ["Revenue", Paragraph(_esc(bp.revenue), styles["TableCell"])],
        ["Growth", Paragraph(_esc(bp.growth), styles["TableCell"])],
        ["Margin", Paragraph(_esc(bp.margin), styles["TableCell"])],
        ["Cash", Paragraph(_esc(bp.cash), styles["TableCell"])],
    ]
    table = Table(rows, colWidths=[1.3 * inch, 4.7 * inch])
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    flow = [Paragraph("Business Performance", styles["SectionHeading"]), table]
    if bp.key_operational_metrics:
        flow.append(Spacer(1, 6))
        flow.append(
            ListFlowable([ListItem(Paragraph(_esc(m), styles["Normal"])) for m in bp.key_operational_metrics], bulletType="bullet")
        )
    return flow


def _concerns(ctx: ReportContext, styles) -> list:
    if not ctx.concerns:
        return []

    flow = [Paragraph("Key Concerns", styles["SectionHeading"])]
    for c in ctx.concerns:
        color = _SEVERITY_COLORS.get(c.severity, colors.grey)
        flow.append(
            Paragraph(
                f'<font color="{color.hexval()}">●</font> {_esc(c.title)} — {_esc(c.severity)} (confidence: {_esc(c.confidence)})',
                styles["SubHeading"],
            )
        )
        if c.business_impact:
            flow.append(Paragraph(f"<b>Impact:</b> {_esc(c.business_impact)}", styles["Normal"]))
        if c.recommended_action:
            flow.append(Paragraph(f"<b>Recommended action:</b> {_esc(c.recommended_action)}", styles["Normal"]))
        root_causes = [h for h in ctx.hypotheses if h.id in (c.root_cause_hypothesis_ids or [])]
        if root_causes:
            flow.append(Paragraph("<b>Root-cause hypotheses:</b>", styles["Normal"]))
            flow.append(
                ListFlowable(
                    [ListItem(Paragraph(f"{_esc(h.statement)} ({_esc(h.status)})", styles["Normal"])) for h in root_causes],
                    bulletType="bullet",
                )
            )
        flow.append(Spacer(1, 8))
    return flow


def _opportunities(ctx: ReportContext, styles) -> list:
    if not ctx.opportunities:
        return []

    flow = [Paragraph("Key Opportunities", styles["SectionHeading"])]
    for o in ctx.opportunities:
        flow.append(Paragraph(f"{_esc(o.title)} (confidence: {_esc(o.confidence)})", styles["SubHeading"]))
        flow.append(Paragraph(_esc(o.rationale), styles["Normal"]))
        if o.next_step:
            flow.append(Paragraph(f"<b>Next step:</b> {_esc(o.next_step)}", styles["Normal"]))
        if o.risks:
            flow.append(Paragraph(f"<b>Risks:</b> {_esc(o.risks)}", styles["Normal"]))
        flow.append(Spacer(1, 8))
    return flow


def _strategic_options(ctx: ReportContext, styles) -> list:
    if not ctx.synthesis.strategic_options:
        return []

    flow = [Paragraph("Strategic Options", styles["SectionHeading"])]
    for opt in ctx.synthesis.strategic_options:
        flow.append(Paragraph(f"{_esc(opt.option)} — feasibility: {opt.feasibility.value}", styles["SubHeading"]))
        flow.append(Paragraph(f"<b>Upside:</b> {_or_not_stated(opt.upside)}", styles["Normal"]))
        flow.append(Paragraph(f"<b>Downside:</b> {_or_not_stated(opt.downside)}", styles["Normal"]))
        flow.append(Paragraph(f"<b>Investment:</b> {_or_not_stated(opt.investment)}", styles["Normal"]))
        flow.append(Paragraph(f"<b>Risks:</b> {_or_not_stated(opt.risks)}", styles["Normal"]))
        flow.append(Paragraph(f"<b>Recommendation:</b> {_or_not_stated(opt.recommendation)}", styles["Normal"]))
        flow.append(Spacer(1, 8))
    return flow


def _or_not_stated(text: str) -> str:
    # These fields are typed as required strings, but an LLM can still return
    # "" for one it had nothing to say about — confirmed live: a blank
    # "Recommendation:" line reads as a rendering bug even though it isn't one.
    # Escapes for the same reason every other dynamic value does (see _esc).
    return _esc(text.strip()) if text and text.strip() else "(not stated)"


def _action_plan(ctx: ReportContext, styles) -> list:
    if not ctx.synthesis.ninety_day_plan:
        return []

    header = ["Action", "Data needed", "KPI", "Expected impact"]
    rows = [header] + [
        [
            Paragraph(_esc(item.action), styles["TableCell"]),
            Paragraph(_esc(item.data_requirements) or "—", styles["TableCell"]),
            Paragraph(_esc(item.kpi) or "—", styles["TableCell"]),
            Paragraph(_esc(item.expected_impact) or "—", styles["TableCell"]),
        ]
        for item in ctx.synthesis.ninety_day_plan
    ]
    table = Table(rows, colWidths=[1.7 * inch, 1.5 * inch, 1.1 * inch, 1.7 * inch], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFEFEF")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return [Paragraph("90-Day Action Plan", styles["SectionHeading"]), table]


def _missing_information(items: list[str], styles) -> list:
    if not items:
        return []
    flow = [Paragraph("Missing Information", styles["SectionHeading"])]
    flow.append(ListFlowable([ListItem(Paragraph(_esc(i), styles["Normal"])) for i in items], bulletType="bullet"))
    return flow


def _financial_appendix(ctx: ReportContext, styles) -> list:
    if not ctx.financial_analysis.periods:
        return []

    header = ["Period", "Revenue", "COGS", "Gross Margin", "EBITDA Margin"]
    rows = [header]
    for p in ctx.financial_analysis.periods:
        rows.append(
            [
                p.period,
                f"{p.revenue:,.0f}" if p.revenue is not None else "—",
                f"{p.cogs:,.0f}" if p.cogs is not None else "—",
                f"{p.gross_margin:.1%}" if p.gross_margin is not None else "—",
                f"{p.ebitda_margin:.1%}" if p.ebitda_margin is not None else "—",
            ]
        )
    table = Table(rows, colWidths=[1 * inch, 1.2 * inch, 1.2 * inch, 1.3 * inch, 1.3 * inch], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFEFEF")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return [PageBreak(), Paragraph("Appendix: Financial Data", styles["SectionHeading"]), table]
